### ISSUE TITLE
Remove index.babel.js

### ISSUE THREAD

**Issue by piranna** [arve0/system-install#2]
Beyond the usage of the `const` keyword that's already available in Node.js, there's no reason to not use vanilla Javascript.

**Comment by arve0** [comment]
I prefer writing in ES2015 and don't mind having the extra compile to support node 0.x out of the box. It's only a dev dependency, so it doesn't add bloat to users.

**Comment by piranna** [comment]
I was not thinking about bloating users but about clean code, I also prefer to write ES2015 code but don't worry anymore for 0.x clients in new code since they are already obsolete, so it doesn't makes sense to use babel here instead of vanilla Javascript.

**Comment by arve0** [comment]
Ubuntu LTS 14.04 has node `0.10.25` which has end of life ~2019. Will `'use strict';` be enough for node `0.10`? (I did not know as of when I made this, and therefor went the babel route).

**Comment by arve0** [comment]
Might need `--harmony`?

**Comment by piranna** [comment]
> Ubuntu LTS 14.04 has node 0.10.25 which has end of life ~2019. Will 'use
> strict'; be enough for node 0.10? (I did not know as of when I made this,
> and therefor went the babel route).

I'm not sure, probably it's just enough. In any case, 0.10 is too way old
and deprecated (0.12 is in maintenance mode and will be deprecated in
decembre) and unsupported by almost all libraries, and in fact due to the
fast cycle of Node.js the recommended way to install it is to not use the
Ubuntu version due to its age and securith issues and instead to use the
official NodeSource PPA.

**Comment by piranna** [comment]
> Might need --harmony?

For the const keyword? Yes, it's needed for Node.js <= 0.12.

**Comment by arve0** [comment]
Just checked: https://travis-ci.org/arve0/system-install/jobs/138844669

```
`string template ${literals}`
```

are not supported in 0.10.

As this is a system-tool, I prefer keeping support for node that ships with LTS distributions. If you like, you are welcome to break 0.10 in your own fork 😉

**Comment by piranna** [comment]
> As this is a system-tool, I prefer keeping support for node that ships
> with LTS distributions.

Ok, makes sense... it's only I'm into use vanilla javascript instead of
transpilers when possible, the same way as core Node.js developers and main
npm developers do.
