### ISSUE TITLE
Reversed Merge Issue

### ISSUE THREAD

**Issue by mezerotm** [arve0/system-install#5]
When updating your package.json to reflect the 1.0.0 change to 1.0.1 you seem to have reverted the previous merge.
This commit reflects that: 3ce6c4fa2364bd8b0a92718eac14a7efd5ca6bc6

**Comment by arve0** [comment]
Change has been submitted to wrong file, and I did not notice. `index.babel.js` is the source file. I'll fix it.

**Comment by arve0** [comment]
Fixed in `v1.0.2`.
